### ISSUE TITLE
Docker install - Debian 13 - Error 500 on first connexion

### ISSUE THREAD

**Issue by MCHAmonAmarth** [infobyte/faraday#549]
## Issue Type
 - Bug Re port

## Faraday version
Latest pulled from docker

## Steps to reproduce

Follow docs for CE Docker install.

## Expected results

Error 500 after attempting to connect to localhost:5985

### Debugging tracebacks (current results)

faraday_server  | 2026-09-01T07:00:17+0000 - faraday.server.app - ERROR {Dummy-4} [pid:1] [app.py:1414 - log_exception()]  Exception on / [GET]
faraday_server  | Traceback (most recent call last):
faraday_server  |   File "/src/.venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
faraday_server  |     response = self.full_dispatch_request()
faraday_server  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
faraday_server  |   File "/src/.venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
faraday_server  |     rv = self.handle_user_exception(e)
faraday_server  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
faraday_server  |   File "/src/.venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
faraday_server  |     rv = self.dispatch_request()
faraday_server  |          ^^^^^^^^^^^^^^^^^^^^^^^
faraday_server  |   File "/src/.venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
faraday_server  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
faraday_server  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
faraday_server  | TypeError: create_app.<locals>.index() got an unexpected keyword argument 'text'

## Environment information

Fresh Debian 13 install, latest Docker CE

### Configuration files

No config change

**Comment by ignaciosoto93** [comment]
Thanks for the report. This is the same active regression already tracked in #543. It affects the documented Docker/CE install flow and produces the same HTTP 500 on GET / with the same index() unexpected keyword argument 'text' traceback. Closing this as a duplicate so tracking stays in one place.
